apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: kontroller-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kontroller-role
subjects:
- kind: ServiceAccount
  name: kontroller-sa
  namespace: default
